using ClosedXML.Excel;
using ExcelReportGenerator.Core.Models;
using ExcelReportGenerator.Core.Builders;
using ExcelReportGenerator.Core.Enum;

namespace ExcelReportGenerator.Core.Presets;

public static class ReportPresets
{
    public static ReportOptions Default()
    {
        return ReportOptionsBuilder.Create()
            .WithSheetName("Report")
            .WithTitle("Default Report")
            .EnableFreezeTopRow()
            .EnableAutoFilter()
            .WithHeaderBackground(XLColor.LightBlue)
            .Build();
    }

    public static ReportOptions FinanceSummary(string title, string footer = null)
    {
        return ReportOptionsBuilder.Create()
            .WithSheetName("Finance Summary")
            .WithTitle(title)
            .WithSubtitle("Department: Finance", $"Generated: {DateTime.Now:MMMM yyyy}")
            .WithFooter(footer ?? "Confidential - Internal Use Only")
            .EnableFreezeTopRow()
            .EnableAutoFilter()
            .WithHeaderBackground(XLColor.LightGray)
            .Build();
    }

    public static ReportOptions WithWatermark(string watermarkText)
    {
        return ReportOptionsBuilder.Create()
            .WithTitle("Confidential Report")
            .WithWatermarkText(watermarkText)
            .WithFooter("This document is confidential and intended only for internal use.")
            .WithHeaderBackground(XLColor.Silver)
            .EnableFreezeTopRow()
            .Build();
    }

    public static ReportOptions WithLogoTopCenter(string logoPath)
    {
        return ReportOptionsBuilder.Create()
            .WithTitle("Executive Summary")
            .WithImage(logoPath, ImagePosition.TopCenter)
            .WithSubtitle("Generated: " + DateTime.Now.ToShortDateString())
            .WithFooter("Auto-generated by the system")
            .WithHeaderBackground(XLColor.AliceBlue)
            .EnableFreezeTopRow()
            .EnableAutoFilter()
            .Build();
    }
}
