using ClosedXML.Excel;
using ExcelReportGenerator.Core.Enum;
using ExcelReportGenerator.Core.Models;
using ExcelReportGenerator.Extensions.Builder;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExcelReportGenerator.Extensions.Presets
{
    public static class ReportPresets
    {
        public static ReportOptions Default()
        {
            return ReportOptionsBuilder.Create()
                .WithSheetName("Report")
                .WithTitle("Default Report")
                .EnableFreezeTopRow()
                .EnableAutoFilter()
                .WithHeaderBackground(XLColor.LightBlue)
                .Build();
        }

        public static ReportOptions FinanceSummary(string title, string footer = null)
        {
            return ReportOptionsBuilder.Create()
                .WithSheetName("Finance Summary")
                .WithTitle(title)
                .WithSubtitle("Department: Finance", $"Generated: {DateTime.Now:MMMM yyyy}")
                .WithFooter(footer ?? "Confidential - Internal Use Only")
                .EnableFreezeTopRow()
                .EnableAutoFilter()
                .WithHeaderBackground(XLColor.LightGray)
                .Build();
        }

        public static ReportOptions WithWatermark(string watermarkText)
        {
            return ReportOptionsBuilder.Create()
                .WithTitle("Confidential Report")
            .WithWatermarkText(watermarkText)
                .WithFooter("This document is confidential and intended only for internal use.")
                .WithHeaderBackground(XLColor.Silver)
                .EnableFreezeTopRow()
                .Build();
        }

        public static ReportOptions WithLogoTopCenter(string logoPath)
        {
            return ReportOptionsBuilder.Create()
                .WithTitle("Executive Summary")
                .WithImage(logoPath, ImagePosition.TopCenter)
                .WithSubtitle("Generated: " + DateTime.Now.ToShortDateString())
                .WithFooter("Auto-generated by the system")
                .WithHeaderBackground(XLColor.AliceBlue)
                .EnableFreezeTopRow()
                .EnableAutoFilter()
                .Build();
        }
    }
}
